# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Manner-Smoker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Manner-Smoker
  pod 'Alamofire'
  pod 'FSCalendar'
  pod 'KakaoSDK'

  target 'Manner-SmokerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Manner-SmokerUITests' do
    # Pods for testing
  end

end
